name: Run Automation Scripts

on: [push, pull_request]

jobs:
  autogen:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: authenticating pusher
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
          done
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run auto-gen.py
      run: |
        python auto-gen.py
    - name: Commit Changes
      continue-on-error: true
      run: |
        git config --global user.name 'Hello-World-Project-Bot'
        git config --global user.email '<>'
        git status
        git add -A
        git commit -m "Run auto-gen.py"
        git push
